version: '3.8'
services:
  # 1. Frontend Service (Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-tier
    depends_on:
      - backend

  # 2. Backend Service (Django)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge